### ISSUE TITLE
It's appers that Ollama-GUI not work in web entvironment

### ISSUE THREAD

**Issue by sytolk** [ollama-interface/Ollama-Gui#29]
I have run `pnpm install` and 'pnpm run dev' but:
```
Something went wrong with loading the database TypeError: Cannot read properties of undefined (reading 'invoke')
    at invoke (core.js:118:39)
    at _Database.load (index.js:32:29)
    at loadDB (local-database.ts:8:25)
    at index.tsx:9:1
```
Maybe this is the issue:
https://github.com/tauri-apps/tauri/issues/8369

**Comment by TwanLuttik** [comment]
Closing this issue since I released a new version with a overhaul update
